### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by zhemant** [fasferraz/NWu-Non3GPP-5GC#7]
I think this might be helpful to others as there are no installation instruction given and for someone who is starting freshly things may become complex.

```bash
sudo apt insatll libpcsclite-dev

pip3 install serial wheel pycrypto  pyscard swig requests cryptography

git clone https://github.com/mitshell/card.git
cd card
python3 setup.py install
cd ..

git clone https://github.com/mitshell/CryptoMobile.git
cd CryptoMobile/
python3 setup.py install
cd ..
```

This is what worked for me on ubuntu:22.04. You are welcome to improve it.

**Comment by fasferraz** [comment]
Thanks! Added this info to Readme.md
